version: '3'

services:
  db:
    container_name: postgres
    image: postgres:14.2-alpine
    restart: always
    environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: 123456
     POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    volumes:
      - ./database/pg-data:/var/lib/postgresql/data
      
      
